# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Live' do
pod 'SVProgressHUD'
pod 'TextAttributes'
pod 'R.swift'
pod 'IHKeyboardAvoiding'
pod 'Socket.IO-Client-Swift'
pod 'LFLiveKit'
end
